## START COPYRIGHT NOTICE ##
# Ansible-Python-AWSCLI-Boto-Deploy-Role
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
## END COPYRIGHT NOTICE ##

# Amazon Linux 2 Distro

# Python3
- name: "Install Python3 | Amazon Linux 2 Distro"
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - python3
    - python3-pip
    - python3-setuptools
    - python3-libs
  register: python3
  ignore_errors: yes
  become: yes
  when:
    - auto_install_latest or (install_python3_only and not install_python2_only)

- name: "Install Python 3 - virtualenv via pip | --upgrade | Amazon Linux 2 Distro"
  shell: "pip3 install --upgrade virtualenv"
  become: yes
  ignore_errors: yes
  when:
    - auto_install_latest or (install_python3_only and not install_python2_only)

- name: "Install Python 3 - virtualenv via pip | --user --upgrade | Amazon Linux 2 Distro"
  shell: "pip3 install --user --upgrade virtualenv"
  become: yes
  ignore_errors: yes
  when:
    - auto_install_latest or (install_python3_only and not install_python2_only)

- name: "Install Python 3 - boto, boto3, botocore via pip | --upgrade | Amazon Linux 2 Distro"
  shell: "pip3 install --upgrade boto"
  become: yes
  ignore_errors: yes
  when:
    - auto_install_latest or (install_python3_only and not install_python2_only) or install_boto

- name: "Install Python 3 - boto, boto3, botocore via pip | --user --upgrade | Amazon Linux 2 Distro"
  shell: "pip3 install --user --upgrade boto"
  become: yes
  ignore_errors: yes
  when:
    - auto_install_latest or (install_python3_only and not install_python2_only) or install_boto

# Python2
- name: "Install Python2 | Amazon Linux 2 Distro"
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - python
    - python2-pip
    - python2-setuptools
    - python-libs
    - python-virtualenv
  register: python2
  ignore_errors: yes
  become: yes
  when:
    - auto_install_latest or (install_python2_only and not install_python3_only)

- name: "Install Python2 - botocore and boto3 | Amazon Linux 2 Distro"
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - python2-botocore
    - python2-boto3
  register: python2_boto
  ignore_errors: yes
  become: yes
  when:
    - auto_install_latest or (install_python2_only and not install_python3_only) or install_boto

- name: "Install Python 2 - boto, boto3, botocore via pip | --upgrade | Amazon Linux 2 Distro"
  shell: "pip install --upgrade boto boto3 botocore"
  become: yes
  ignore_errors: yes
  when:
    - auto_install_latest or (install_python2_only and not install_python3_only) or install_boto

- name: "Install Python 2 - boto, boto3, botocore via pip | --user --upgrade | Amazon Linux 2 Distro"
  shell: "pip install --user --upgrade boto boto3 botocore"
  become: yes
  ignore_errors: yes
  when:
    - auto_install_latest or (install_python2_only and not install_python3_only) or install_boto

- name: "Install AWSCLI - bundled installer | Amazon Linux 2 Distro"
  shell: "{{ item }}"
  args:
    chdir: "/tmp/"
  become: yes
  ignore_errors: yes
  with_items:
    - "curl \"https://s3.amazonaws.com/aws-cli/awscli-bundle.zip\" -o \"awscli-bundle.zip\""   
    - "unzip awscli-bundle.zip"
    - "sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws"
  when:
    - auto_install_latest or install_python2_only or install_python3_only or install_awscli
