## START COPYRIGHT NOTICE ##
# Ansible-Python-AWSCLI-Boto-Deploy-Role
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
## END COPYRIGHT NOTICE ##

# Debian or Ubuntu Distros

- name: "Update apt repo list | Debian or Ubuntu Distros"
  shell: "apt-get update"
  become: yes

# Python3
- name: "Install Python3 | Debian or Ubuntu Distros"
  shell: "apt-get install -y python3 python3-pip python3-virtualenv"
  become: yes
  ignore_errors: yes
  register: python3
  when:
    - auto_install_latest or (install_python3_only and not install_python2_only)

- name: "Install Python3 - boto, botocore, boto3 | Debian or Ubuntu Distros"
  shell: "apt-get install -y python3-boto python3-botocore python3-boto3"
  become: yes
  ignore_errors: yes
  register: python3_boto
  when:
    - auto_install_latest or (install_python3_only and not install_python2_only) or install_boto

# Python2
- name: "Install Python2 | Debian or Ubuntu Distros"
  shell: "apt-get install -y python python-pip python-virtualenv"
  become: yes
  ignore_errors: yes
  register: python2
  when:
    - auto_install_latest or (install_python2_only and not install_python3_only)

- name: "Install Python2 - boto, botocore, boto3 | Debian or Ubuntu Distros"
  shell: "apt-get install -y python-boto python-botocore python-boto3"
  become: yes
  ignore_errors: yes
  register: python2_boto
  when:
    - auto_install_latest or (install_python3_only and not install_python2_only) or install_boto

- name: "Install AWSCLI - bundled installer | Debian or Ubuntu Distros"
  shell: "{{ item }}"
  args:
    chdir: "/tmp/"
  become: yes
  ignore_errors: yes
  with_items:
    - "curl \"https://s3.amazonaws.com/aws-cli/awscli-bundle.zip\" -o \"awscli-bundle.zip\""   
    - "unzip awscli-bundle.zip"
    - "sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws"
  when:
    - auto_install_latest or install_python2_only or install_python3_only or install_awscli